### PR TITLE
Let's merge!

### PR DESCRIPTION
**Pull request by mr-islam**
Just pasting the email here:

I saw your fork in the morning, and learned a lot actually! I never knew that we can make a separate file and 'import' things from it like a library, and the lower() function seems nice to have. And your way is a better for the OSX command, although I think you added a few apostrophes too many! ([this was my source for the command](http://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel/115373#115373))

I've read about forks on GitHub now as well, and I'd love to merge your changes; and I have a few new ideas as well! it's awesome how looking at someone else's work also creates so many ideas.

### CODE REVIEW

**Comment by ragerin** [comment]
Perfect! :-) 
Yes, I never got the OSX bit to work either, but i honestly spent most of the time trying to spin up a VM with OSX.

**Comment by ragerin** [comment]
So, I reckon the OSX bit should be removed, until we find a good solution for that. I will be able to conduct some testing on OSX soon.

**Comment by mr-islam** [comment]
I got some ideas as well for OSX; I'll make a new branch for this testing (and also the Windows-solution you found), and take out the OSX from the master branch then.

**Comment by mr-islam** [comment]
I edited the OSX command on the `testing` branch carefully; all those apostrophes hurt haha. It _should_ work now. Do add the Windows solution to the branch when you get time :)

**Pull request merged**
